### ISSUE TITLE
error while running test

### ISSUE THREAD

**Issue by piyusharorawork** [excalidraw/excalidraw#2738]
I am useing node version 14.15.0

after running npm run test , I got following error
sharing the log dump
`
  Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
          at App (/Users/piyusharora/projects/open-source/excalidraw/src/components/App.tsx:267:5)
          at IsMobileProvider (/Users/piyusharora/projects/open-source/excalidraw/src/is-mobile.tsx:6:3)
          at InitializeApp (/Users/piyusharora/projects/open-source/excalidraw/src/components/InitializeApp.tsx:17:66)
          at Excalidraw (/Users/piyusharora/projects/open-source/excalidraw/src/packages/excalidraw/index.tsx:15:5)
          at ExcalidrawWrapper (/Users/piyusharora/projects/open-source/excalidraw/src/excalidraw-app/index.tsx:192:39)
          at CollabWrapper (/Users/piyusharora/projects/open-source/excalidraw/src/excalidraw-app/collab/CollabWrapper.tsx:74:5)
          at TopErrorBoundary (/Users/piyusharora/projects/open-source/excalidraw/src/components/TopErrorBoundary.tsx:15:3)
          at ExcalidrawApp

      3817 | 
      3818 |   private resetShouldCacheIgnoreZoomDebounced = debounce(() => {
    > 3819 |     this.setState({ shouldCacheIgnoreZoom: false });
           |          ^
      3820 |   }, 300);
      3821 | 
      3822 |   private getCanvasOffsets(offsets?: {

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (node_modules/react-dom/cjs/react-dom.development.js:23914:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21840:5)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12467:5)
      at App.setState (node_modules/react/cjs/react.development.js:365:16)
      at fn (src/components/App.tsx:3819:10)
      at src/utils.ts:129:38

Test Suites: 23 passed, 23 total
Tests:       192 passed, 192 total
Snapshots:   409 passed, 409 total
Time:        25.976 s
Ran all test suites.
`

![image](https://user-images.githubusercontent.com/31386968/103891233-7ee18400-510f-11eb-8dcd-7dcfb09a233b.png)

**Comment by dwelle** [comment]
Yea, we get that a lot. I've got a fix locally for this specific error, but during tests there are zillion cases like this. 

It's just a warning and you can ignore it as it's not blocking anything right now.

**Comment by dwelle** [comment]
I'll actually reopen this so we track it.

**Comment by axhamre** [comment]
Here is a reproduction of the same warning message when editing elements:
1. Select an element
2. Change it's stroke or background vallue
3. The warning appears

https://user-images.githubusercontent.com/1907343/112722644-09fe3900-8f0b-11eb-94d5-a5b000b1a2a6.mp4

Version: checked out master 2020-03-27
