### ISSUE TITLE
Warning when running tests

### ISSUE THREAD

**Issue by Rafi993** [excalidraw/excalidraw#2778]
when you run ```npm run test:all``` there is following error in the console

```
 PASS  src/tests/regressionTests.test.tsx (25.869 s)
  ● Console

    console.error
      Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
          at App (/home/rafi/projects/excalidraw/src/components/App.tsx:267:5)
          at IsMobileProvider (/home/rafi/projects/excalidraw/src/is-mobile.tsx:6:3)
          at InitializeApp (/home/rafi/projects/excalidraw/src/components/InitializeApp.tsx:17:66)
          at Excalidraw (/home/rafi/projects/excalidraw/src/packages/excalidraw/index.tsx:15:5)
          at ExcalidrawWrapper (/home/rafi/projects/excalidraw/src/excalidraw-app/index.tsx:198:39)
          at CollabWrapper (/home/rafi/projects/excalidraw/src/excalidraw-app/collab/CollabWrapper.tsx:74:5)
          at TopErrorBoundary (/home/rafi/projects/excalidraw/src/components/TopErrorBoundary.tsx:15:3)
          at ExcalidrawApp

      3817 | 
      3818 |   private resetShouldCacheIgnoreZoomDebounced = debounce(() => {
    > 3819 |     this.setState({ shouldCacheIgnoreZoom: false });
           |          ^
      3820 |   }, 300);
      3821 | 
      3822 |   private getCanvasOffsets(offsets?: {

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnAboutUpdateOnUnmountedFiberInDEV (node_modules/react-dom/cjs/react-dom.development.js:23914:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:21840:5)
      at Object.enqueueSetState (node_modules/react-dom/cjs/react-dom.development.js:12467:5)
      at App.setState (node_modules/react/cjs/react.development.js:365:16)
      at fn (src/components/App.tsx:3819:10)
      at src/utils.ts:130:38

```

**Comment by Rafi993** [comment]
Hi there if this issue is not taken I would like to help :)

**Comment by dwelle** [comment]
Hello. I've had this fixed locally for some time, so I may as well push the fix https://github.com/excalidraw/excalidraw/pull/2779

That said, there are many similar errors. If you identify some of them, and the fix won't be too complex, go ahead and fix those. We track it in https://github.com/excalidraw/excalidraw/issues/2738

**Comment by Rafi993** [comment]
Awesome. Should I close this issue since it looks like it is a duplicate of other issue?

**Comment by dwelle** [comment]
It's fine. It'll be auto-closed when the PR is merged.
