### ISSUE TITLE
The value of property "ciphertext" is longer than 1048487 bytes.

### ISSUE THREAD

**Issue by evan-boissonnot** [excalidraw/excalidraw#4839]
On onlinbe website 
we've got this 

The value of property "ciphertext" is longer than 1048487 bytes.

FirebaseError: The value of property "ciphertext" is longer than 1048487 bytes.
    at new e (prebuilt-4888bff0-430c65bc.js:180:23)
    at mn.<anonymous> (prebuilt-4888bff0-430c65bc.js:9829:35)
    at At (index.esm.js:358:22)
    at St (index.esm.js:338:50)
    at In (index.esm.js:982:36)
    at Tn (index.esm.js:1035:21)
    at mn.Ua (index.esm.js:986:22)
    at mn.za (index.esm.js:985:78)
    at XMLHttpRequest.<anonymous> (instrument.ts:287:29)
    at XMLHttpRequest.r (helpers.ts:87:17)

Seems to freeze all website : unable to share,  white page ...

**Comment by dwelle** [comment]
There's a hard 1MB limit on Firestore documents. We should start compressing data before storing.
