### ISSUE TITLE
! ! console error..when iam trying to call update scene functions inside the use effect 

### ISSUE THREAD

**Issue by Sohailamjad1** [excalidraw/excalidraw#5018]
zone.js:1698 Uncaught TypeError: Cannot read properties of null (reading 'updateScene')
    at updateScene (ngexcalidraw.tsx:135:27)
    at ngexcalidraw.tsx:48:5
    at commitHookEffectListMount (react-dom.development.js:19866:28)
    at commitPassiveHookEffects (react-dom.development.js:19904:13)
    at HTMLUnknownElement.callCallback (react-dom.development.js:182:16)
    at _ZoneDelegate.invokeTask (zone.js:406:1)
    at Zone.runTask (zone.js:178:1)
    at ZoneTask.invokeTask [as invoke] (zone.js:487:1)
    at invokeTask (zone.js:1648:1)
    at globalCallback (zone.js:1679:1)
    at HTMLUnknownElement.globalZoneAwareCallback (zone.js:1712:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:231:18)
    at invokeGuardedCallback (react-dom.development.js:286:33)
    at flushPassiveEffectsImpl (react-dom.development.js:22988:11)
    at unstable_runWithPriority (react.development.js:2685:14)
    at runWithPriority$1 (react-dom.development.js:11174:12)
    at flushPassiveEffects (react-dom.development.js:22955:14)
    at react-dom.development.js:22834:13
    at workLoop (react.development.js:2629:36)
    at flushWork (react.development.js:2584:18)
    at MessagePort.performWorkUntilDeadline (react.development.js:2196:29)

This is the error  please help ....Thanks

**Comment by Sohailamjad1** [comment]
Hey ...can you please check

**Comment by ad1992** [comment]
@Sohailamjad1 please try putting a debugger in the line where the error occurs, this doesn't look like related to excalidraw but the data which is passed to `updateScene` probably is `null`

**Comment by Sohailamjad1** [comment]
Hi i debug that isssue ..when we calling update scene from that line that is breaking..and i update scene im passing drawing data
const updateScene = () => {
    console.log('props.eleData',props.eleData)
    props.eleData
    excalidrawRef.current.updateScene(props.eleData);
  };
