### ISSUE TITLE
DOMException at at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController$initJcefPanel$5.onConsoleMessage(ExcalidrawWebViewController.kt:219)

### ISSUE THREAD

**Issue by lestephane** [excalidraw/excalidraw#5094]
v0.3.2

```
java.lang.Throwable: [LOGSEVERITY_ERROR][https://excalidraw-jetbrains-plugin/index.html:12174]:
[object DOMException]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:182)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController$initJcefPanel$5.onConsoleMessage(ExcalidrawWebViewController.kt:219)
	at com.intellij.ui.jcef.JBCefClient$3.lambda$onConsoleMessage$4(JBCefClient.java:297)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$0(JBCefClient.java:715)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2067)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:715)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleBoolean(JBCefClient.java:720)
	at com.intellij.ui.jcef.JBCefClient$3.onConsoleMessage(JBCefClient.java:296)
	at jcef/org.cef.CefClient.onConsoleMessage(CefClient.java:308)
```

**Comment by ad1992** [comment]
@lestephane this looks like related to JetBrains integration, so you will need to open an issue there
