### ISSUE TITLE
[NPM Package] Crash when adding a new point in the line editor

### ISSUE THREAD

**Issue by pomdtr** [excalidraw/excalidraw#5602]
I use the alt shortcut to add the new point, then release the alt-key without clicking. Here is a demo on the latest master commit:

https://user-images.githubusercontent.com/17577332/185786184-dc689cd2-40c6-4408-9eb0-886549ef0c9e.mov

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at LinearElementEditor.getPointAtIndexGlobalCoordinates (VM94 linearElementEditor.ts:366:71)
    at renderLinearElementPointHighlight (VM90 renderScene.ts:164:97)
    at _renderScene (VM90 renderScene.ts:257:9)
    at renderScene (VM90 renderScene.ts:465:17)
    at App.renderScene (VM40 App.tsx:396:80)
    at App.componentDidUpdate (VM40 App.tsx:3146:14)
    at commitLayoutEffectOnFiber (react-dom.development.js:23348:30)
    at commitLayoutMountEffects_complete (react-dom.development.js:24698:11)
    at commitLayoutEffects_begin (react-dom.development.js:24684:9)
    at commitLayoutEffects (react-dom.development.js:24622:5)
```

**Comment by zsviczian** [comment]
@pomdtr I am debugging #5604 Are you using Excalidraw with React 18 or 17?

**Comment by pomdtr** [comment]
@zsviczian I'm using react 17, see https://github.com/excalidraw/excalidraw-vscode/blob/master/webview/package.json

**Comment by zsviczian** [comment]
![image](https://user-images.githubusercontent.com/14358394/185806483-ace3cc36-194d-4e4d-a980-bae2f8c4e18a.png)
