### ISSUE TITLE
__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED

### ISSUE THREAD

**Issue by josephp27** [excalidraw/excalidraw#5680]
Hi, I seem to be getting this weird error when I attempt to embed excalidraw as a component in my app:

```
react-jsx-runtime.development.js?fc5c:85 
        
       Uncaught TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
    at eval (react-jsx-runtime.development.js?fc5c:85:1)
    at eval (react-jsx-runtime.development.js?fc5c:1220:4)
    at ../../../node_modules/react/cjs/react-jsx-runtime.development.js (excalidraw.development.js:406:1)
    at __webpack_require__ (excalidraw.development.js:3522:42)
    at eval (jsx-runtime.js?06ac:6:3)
    at ../../../node_modules/react/jsx-runtime.js (excalidraw.development.js:417:1)
    at __webpack_require__ (excalidraw.development.js:3522:42)
    at eval (index.tsx:36:75)
    at ./index.tsx (excalidraw.development.js:3146:1)
    at __webpack_require__ (excalidraw.development.js:3522:42)
```

**Comment by dwelle** [comment]
Hi. How are you embedding the Excalidraw (can you show code, including imports)? Are you using the npm (which version)?

Alternatively, can you create a [CodeSandbox](https://react.new/) example that reproduces this error? This would be best.

**Comment by josephp27** [comment]
Hi, thanks for the help!

So I'm using yarn version 1.22.19

```javascript


import { Button, useColorMode } from "@chakra-ui/react";
import { Excalidraw } from "@excalidraw/excalidraw";
import { ExcalidrawImperativeAPI } from "@excalidraw/excalidraw/types/types";
import { useEffect, useRef } from "react";

export default function Whiteboard() {
  const { colorMode } = useColorMode();
  const excalidrawRef = useRef<ExcalidrawImperativeAPI>(null);

  useEffect(() => {
    excalidrawRef?.current?.updateScene({
      appState: {
        theme: colorMode,
        viewBackgroundColor: colorMode === "light" ? "#ffffff" : "#f1f3f3",
      },
    });
  }, [colorMode]);

  return (
    <Excalidraw
      initialData={{
        appState: {
          theme: colorMode,
          viewBackgroundColor: colorMode === "light" ? "#ffffff" : "#f1f3f3",
        },
      }}
      UIOptions={{
        canvasActions: {
          export: {
            saveFileToDisk: false,
            renderCustomUI: () => <Button>Hi!!!!</Button>,
          },
        },
      }}
      theme={colorMode}
      ref={excalidrawRef}
      onPointerUpdate={(payload) => console.log(payload)}
      onCollabButtonClick={() => window.alert("You clicked on collab button")}
    />
  );
}
```

I could not replicate on codesandbox

**Comment by dwelle** [comment]
Looks fine to me.

Also sorry, I meant to say "Are you using the npm [excalidraw package], and which version". I assume stable (`yarn add @excalidraw/excalidraw`)?

And what about React version?

**Comment by 7flash** [comment]
Happens to me when using importing in NextJS:

```
        <Script
          src="/excalidraw.development.js"
          strategy="beforeInteractive"
        />

```

**Comment by riceyeh** [comment]
I have this problem also. But I git clone excalidraw and build it, then I pnpm install the local built excalidraw in my project. When running project and access the page with excalidraw, this problem hasspns.
