### ISSUE TITLE
__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED

### ISSUE THREAD

**Issue by riceyeh** [excalidraw/excalidraw#6379]
I have the same problem as issue #5680. I git clone excalidraw and build it, then I 'pnpm install' the local built excalidraw in my project. When running project and access the page with excalidraw, this problem happens. The following is the stack trace:

react-jsx-runtime.development.js?fc5c:52 Uncaught TypeError: Cannot read properties of undefined (reading '__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED')
    at eval (react-jsx-runtime.development.js?fc5c:52:1)
    at eval (react-jsx-runtime.development.js?fc5c:1313:4)
    at Object.node_modulesReactCjsReactJsxRuntimeDevelopmentJs [as ../../../node_modules/react/cjs/react-jsx-runtime.development.js] (excalidraw.development.js:396:1)
    at __nested_webpack_require_7894944__ (excalidraw.development.js:4224:41)
    at eval (jsx-runtime.js?06ac:6:3)
    at Object.node_modulesReactJsxRuntimeJs [as ../../../node_modules/react/jsx-runtime.js] (excalidraw.development.js:407:1)
    at __nested_webpack_require_7894944__ (excalidraw.development.js:4224:41)
    at eval (index.tsx:44:75)
    at Object.indexTsx [as ./index.tsx] (excalidraw.development.js:3760:1)
    at __nested_webpack_require_7894944__ (excalidraw.development.js:4224:41)

**Comment by riceyeh** [comment]
This problem seems caused by webpack for duplicate react.
