### ISSUE TITLE
firebase error on app when adding a comment

### ISSUE THREAD

**Issue by LeonFedotov** [excalidraw/excalidraw#6522]
when adding a comment im getting 
```
ene snapshot subscription error FirebaseError: Missing or insufficient permissions.
    at new t (main.dc475ca7.js:2:2251398)
    at main.dc475ca7.js:2:2395201
    at main.dc475ca7.js:2:2395224
    at t.onMessage (main.dc475ca7.js:2:2396048)
    at main.dc475ca7.js:2:2393836
    at main.dc475ca7.js:2:2394268
    at main.dc475ca7.js:2:2328258
(
```

and 
```
rebaseError: Missing or insufficient permissions.
    at new t (main.dc475ca7.js:2:2251398)
    at main.dc475ca7.js:2:2395201
    at main.dc475ca7.js:2:2395224
    at t.onMessage (main.dc475ca7.js:2:2396048)
    at main.dc475ca7.js:2:2393836
    at main.dc475ca7.js:2:2394268
    at main.dc475ca7.js:2:2328258
(
```

**Comment by LeonFedotov** [comment]
this error is due to my user not having permission on a document that i didnt create, would love seeing some description though ^_^
