### ISSUE TITLE
Exception IntelliJ 2023.1 / Excalidraw 0.3.2

### ISSUE THREAD

**Issue by abentele** [excalidraw/excalidraw#6524]
I have this exception after installing Excalidraw Plugin in IntelliJ; it prevents rendering my Asciidoc files including diagrams.

```
Unhandled exception in [StandaloneCoroutine{Cancelling}@27bd0d04, Dispatchers.Default]

java.lang.NullPointerException: Cannot invoke "org.cef.browser.CefFrame.getURL()" because the return value of "org.cef.browser.CefBrowser.getMainFrame()" is null
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.runJS(ExcalidrawWebViewController.kt:352)
	at com.github.bric3.excalidraw.editor.ExcalidrawWebViewController.saveAsCoroutines(ExcalidrawWebViewController.kt:333)
	at com.github.bric3.excalidraw.editor.ExcalidrawEditor$saveCoroutines$1.invokeSuspend(ExcalidrawEditor.kt:210)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelled}@27bd0d04, Dispatchers.Default]
```

**Comment by ad1992** [comment]
@abentele please open this issue in https://github.com/bric3/excalidraw-jetbrains-plugin
cc @bric3
