### ISSUE TITLE
Unable to upgrade to v17.0 (jsxs undefined error)

### ISSUE THREAD

**Issue by p2gdeveloper** [excalidraw/excalidraw#7330]
I have encountered an issue that prevents me from upgrading excalidraw to v17.0 in my host app. When I try, on page load I get the error: "Cannot read properties of undefined (reading 'jsxs')". If I try to force past that I then get "ExcalidrawLib is not defined".

My setup with v16.1 (which works well) is:

	const [excalidrawAPI, setExcalidrawAPI] = React.useState(null);

	React.createElement(ExcalidrawLib.Excalidraw, {
	  initialData: vText,
	  ref: (api) => setExcalidrawAPI(api),
	  ...
  
 Now, with v17.0, I am trying:
 
	const [excalidrawAPI, setExcalidrawAPI] = React.useState(null);
 
 	React.createElement(ExcalidrawLib.Excalidraw, {
	  initialData: vText,
	  excalidrawAPI: (api) => setExcalidrawAPI(api),
	  ...
	  
What am I doing wrong?
	  
Note that my environment does not support the import/export of components.

**Comment by 7flash** [comment]
Same, following docs results in this error, to reproduce copy code example: https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#browser

```
Uncaught TypeError: Cannot read properties of undefined (reading 'jsxs')
    at eval (icons.tsx:74:41)
    at ../../components/icons.tsx (excalidraw.development.js:3588:1)
    at __webpack_require__ (excalidraw.development.js:5614:42)
    at eval (Hyperlink.tsx:21:75)
    at ../../element/Hyperlink.tsx (excalidraw.development.js:3852:1)
    at __webpack_require__ (excalidraw.development.js:5614:42)
    at eval (renderScene.ts:22:77)
    at ../../renderer/renderScene.ts (excalidraw.development.js:4424:1)
    at __webpack_require__ (excalidraw.development.js:5614:42)
    at eval (transformHandles.ts:13:79)
```
