### ISSUE TITLE
The latest (0.17.0) library in https://unpkg.com/@excalidraw/excalidraw does not work

### ISSUE THREAD

**Issue by mdaxf** [excalidraw/excalidraw#7366]
The latest (0.17.0) library in https://unpkg.com/@excalidraw/excalidraw does not work with the browser with the jsxs error.  But the 0.16.0 version works.  Could your team generate a new version to support the browser? Thanks.

**Comment by ad1992** [comment]
@mdaxf please use `0.17.1` version of the library and it will work

**Comment by mdaxf** [comment]
@ad1992, Thanks.  When using excalidraw in the browser, how do you get the excalidrawAPI objects?

**Comment by 7flash** [comment]
Following works with excalidraw 0.17.1:

```
<!DOCTYPE html>
<html>
  <head>
    <title>Excalidraw in browser</title>
    <meta charset="UTF-8" />
    <script src="https://unpkg.com/react@18.2.0/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.development.js"></script>
    <script
      type="text/javascript"
      src="https://unpkg.com/@excalidraw/excalidraw@0.17.1/dist/excalidraw.development.js"
    ></script>
  </head>

  <body>
  <h1>December 1</h1>
    <div class="container">
      <div id="app"></div>
    </div>
<script type="text/javascript">
  window.onload = function () {
    const App = () => {
      return React.createElement(
        React.Fragment,
        null,
        React.createElement(
          "div",
          {
            style: { height: "100vh", width: "100vw" },
          },
          React.createElement(ExcalidrawLib.Excalidraw),
        ),
      );
    };

    const excalidrawWrapper = document.getElementById("app");
    const root = ReactDOM.createRoot(excalidrawWrapper);
    root.render(React.createElement(App));
  };
</script>

  </body>
</html>
```

**Comment by 7flash** [comment]
But unfortunately doesn't work with Preact, it cannot find ExcalidrawLib again

```
<!DOCTYPE html>
<html>
  <head>
    <title>Excalidraw in browser</title>
    <meta charset="UTF-8" />
    <script src="https://unpkg.com/preact@10.19.2/dist/preact.umd.js"></script>
    <script
      type="text/javascript"
      src="https://unpkg.com/@excalidraw/excalidraw@0.17.1/dist/excalidraw-with-preact.development.js"
    ></script>
  </head>

  <body>
  <h1>December 1</h1>
    <div class="container">
      <div id="app"></div>
    </div>
<script type="text/javascript">
  window.onload = function () {
    const App = () => {
      return preact.h(
        preact.Fragment,
        null,
        preact.h(
          "div",
          {
            style: { height: "100vh", width: "100vw" },
          },
          preact.h(ExcalidrawLib.Excalidraw),
        ),
      );
    };

    const excalidrawWrapper = document.getElementById("app");
    preact.render(preact.h(App), excalidrawWrapper);
  };
</script>
  </body>
</html>

```

**Comment by ad1992** [comment]
@7flash you need to make sure that env variable `process.env._IS_PREACT` is accessible  (and it should be string `"true")`then it will work with Preact too - https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#preact

**Comment by 7flash** [comment]
> https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#preact

In example above I am not using vite, but just importing build excalidraw-with-preact.development.js directly

**Comment by ad1992** [comment]
> > https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#preact
> 
> In example above I am not using vite, but just importing build excalidraw-with-preact.development.js directly

Does it throw any error in the console? Can you share a CSB link with the example so I can look into it? I had tested with bundler and it worked well with Preact.

**Comment by 7flash** [comment]
> > > https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#preact
> > 
> > 
> > In example above I am not using vite, but just importing build excalidraw-with-preact.development.js directly
> 
> Does it throw any error in the console? Can you share a CSB link with the reproducible example so I can look into it? I had tested with bundler and it worked well with Preact.

https://codesandbox.io/p/sandbox/solitary-architecture-lg7n9h

**Comment by ggrossetie** [comment]
This issue seems to be back in 0.17.2. It was fixed in 0.17.1 but I get the following error with 0.17.2:

```
icons.tsx:212 Uncaught TypeError: Cannot read properties of undefined (reading 'jsxs')
    at eval (icons.tsx:212:84)
    at ../../components/icons.tsx (excalidraw.development.js:3588:1)
    at __webpack_require__ (excalidraw.development.js:5614:42)
    at eval (Hyperlink.tsx:21:75)
    at ../../element/Hyperlink.tsx (excalidraw.development.js:3852:1)
    at __webpack_require__ (excalidraw.development.js:5614:42)
    at eval (renderScene.ts:22:77)
    at ../../renderer/renderScene.ts (excalidraw.development.js:4424:1)
    at __webpack_require__ (excalidraw.development.js:5614:42)
    at eval (transformHandles.ts:13:79)
```

```html
<html>
  <head>
    <script src="https://unpkg.com/react@18.2.0/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.development.js"></script>
    <script
      type="text/javascript"
      src="https://unpkg.com/@excalidraw/excalidraw@0.17.2/dist/excalidraw.development.js"
    ></script>
</head>
<body>
</body>
</html>
```
