### ISSUE TITLE
Docker compose throws cross-env: not found

### ISSUE THREAD

**Issue by diminDDL** [excalidraw/excalidraw#7464]
After following the instructions on https://docs.excalidraw.com/docs/introduction/development to run a docker container from the compose file, I get the following error:
```
=> ERROR [build 6/6] RUN yarn build:app:docker                                                                                                              0.6s
------                                                                                                                                                            
 > [build 6/6] RUN yarn build:app:docker:                                                                                                                         
0.442 yarn run v1.22.19                                                                                                                                           
0.460 $ cross-env VITE_APP_DISABLE_SENTRY=true VITE_APP_DISABLE_TRACKING=true vite build                                                                          
0.468 /bin/sh: 1: cross-env: not found
0.477 error Command failed with exit code 127.
0.478 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:11
--------------------
   9 |     
  10 |     COPY . .
  11 | >>> RUN yarn build:app:docker
  12 |     
  13 |     FROM nginx:1.21-alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build:app:docker" did not complete successfully: exit code: 127
ERROR: Service 'excalidraw' failed to build : Build failed
```

**Comment by iferc** [comment]
Looks like the `cross-env` dependency was accidentally removed in https://github.com/excalidraw/excalidraw/commit/d6cd8b78f11742e9107dd4cd9cee564120ae599b#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L23

Probably anyone who had their `node_modules` already built when it was removed wouldn't have hit this issue.

Unfortunately adding `"cross-env": "7.0.3",` back into the `package.json` file led me to a new error that `@rollup/rollup-linux-x64-gnu` is missing. I tried adding that as a dependency as well but that only got me this new error:

```
0.389 yarn run v1.22.19
0.415 $ cross-env VITE_APP_DISABLE_SENTRY=true VITE_APP_DISABLE_TRACKING=true vite build
0.676 vite v5.0.6 building for production...
0.696 ✓ 0 modules transformed.
0.698 Could not resolve entry module "index.html".
0.698 error during build:
0.698 RollupError: Could not resolve entry module "index.html".
0.698     at error (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
0.698     at ModuleLoader.loadEntryModule (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:17957:20)
0.698     at async Promise.all (index 0)
0.717 error Command failed with exit code 1.
0.718 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Interestingly I get that exact same error on `v0.17.0` and `v0.16.1`. I'm not sure if the `Dockerfile` has maybe been broken for a good while outside of this new issue.

It seemed like it might be related to `excalidraw-app` being excluded via `.dockerignore`. Changing the `.dockerignore` file to include `excalidrwa-app` threw a new error about a missing dependency.

Finally I tried changing the `Dockerfile` to use `RUN yarn --cwd ./excalidraw-app build:app:docker` like the `package.json` does in some spots. The missing `index.html` error is replaced by the following:

```
1.896 [vite-plugin-pwa:build] [vite]: Rollup failed to resolve import "clsx" from "/opt/node_app/excalidraw-app/App.tsx".
1.896 This is most likely unintended because it can break your application at runtime.
1.896 If you do want to externalize this module explicitly add it to
1.896 `build.rollupOptions.external`
```

Hopefully somebody more familiar with this project might see some clues in this information, or maybe the rabbit hole of dependencies and missing files doesn't go much deeper and another can solve the riddle.

In the meantime, I am okay with an older version and I was able to checkout `v0.15.0` as a version that runs in docker successfully!

Sweet project by the way! I heard folks in a twitch chat recommending it and so far I'm liking `v0.15.0`! Looking forward to when it's solved on `master`.

**Comment by JannikStreek** [comment]
Hi!

First, thanks for the research @iferc . I have had the same problem and did some further research. In the referenced commit, the project was split up into different workspaces, see package.json at the top. This is why the main package.json file was thinned out as the other workspaces package.json files are also installed with the parents install command. Unfortunately, the docker build file is still quite old and outdated and the existing command (`COPY package.json yarn.lock ./`) is no longer sufficient. In addition, the package.json file run commands used in docker are also all outdated [1]. My feeling is, that docker is no longer used in excalidraw. Thats why nothing works anymore. See also the workflow runs with docker [2], everything fails.

Anyway, here is my PR: https://github.com/excalidraw/excalidraw/pull/7502
If you want to test a working setup, I try to keep this fork updated and working: https://github.com/b310-digital/excalidraw

Feel free to test.

[1] =  https://github.com/excalidraw/excalidraw/pull/7430
[2] = https://github.com/excalidraw/excalidraw/actions/workflows/build-docker.yml
