### ISSUE TITLE
Document is not defined

### ISSUE THREAD

**Issue by suzushi-tw** [excalidraw/excalidraw#7573]
Hi, I am slightly new to this, curretly I am getting: 
```
 ⨯ node_modules\@excalidraw\excalidraw\dist\excalidraw.development.js (5780:30) @ eval
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (C:\Users\huang\Desktop\celestialpdf-production\.next\server\webpack-runtime.js:33:43)
    at __webpack_require__ (C:\Users\huang\Desktop\celestialpdf-production\.next\server\webpack-runtime.js:33:43)
    at eval (./src/components/Flowchartdashboard.tsx:24:81)
    at (ssr)/./src/components/Flowchartdashboard.tsx (C:\Users\huang\Desktop\celestialpdf-production\.next\server\app\Flowchartdashboard\page.js:348:1)        
    at __webpack_require__ (C:\Users\huang\Desktop\celestialpdf-production\.next\server\webpack-runtime.js:33:43)
null
```
According to some research we should use dynamic to resolve this issue, unfortunately I wasn't able to solve it, any 
help is appreciated, and here's the component with the error: 
```
'use client'

import { trpc } from '@/app/_trpc/client'
import {
    Ghost,
    Loader2,
    MessageSquare,
    Plus,
    Trash,
} from 'lucide-react'
import Skeleton from 'react-loading-skeleton'
import { Button } from './ui/button'
import { getUserSubscriptionPlan } from '@/lib/stripe'
import { PrismaClient } from '@prisma/client'
import { Input } from './ui/input'
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import React, { ChangeEvent, FormEventHandler } from 'react'
import { useState } from 'react'
import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card"
import { Textarea } from "./ui/textarea"
import { useChat } from 'ai/react';


import 'markmap-toolbar/dist/style.css';
import { Mindmapbutton } from './Mindmapbutton'
import {
    Select,
    SelectContent,
    SelectGroup,
    SelectItem,
    SelectLabel,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select"
import { updatefileselection } from '@/serveractions/action'
import toast, { Toaster } from 'react-hot-toast';
import { ToastAction } from "@/components/ui/toast"
import { useToast } from "@/components/ui/use-toast"
import {
    ResizableHandle,
    ResizablePanel,
    ResizablePanelGroup,
} from "@/components/ui/resizable"
import { parseMermaidToExcalidraw } from "@excalidraw/mermaid-to-excalidraw";
import { convertToExcalidrawElements } from "@excalidraw/excalidraw";
import { useRef, useEffect } from 'react';
import dynamic from "next/dynamic";
import ExcalidrawGuide from './guide/ExcalidrawGuide'

const Excalidraw = dynamic(
    async () => (await import("@excalidraw/excalidraw")).Excalidraw,
    {
        ssr: false,
    },
);

const prisma = new PrismaClient()
interface PageProps {
    subscriptionPlan: Awaited<ReturnType<typeof getUserSubscriptionPlan>>
}


const Flowchartdashboard = ({ subscriptionPlan }: PageProps) => {

    const utils = trpc.useContext();
    const { toast } = useToast()
    const [selectedFileId, setSelectedFileId] = useState('');
    const [isReady, setIsReady] = useState(false);

    const { data: files } = trpc.getUserFiles.useQuery();
    let excalidrawElements = convertToExcalidrawElements([
        {
            type: "rectangle",
            x: 100,
            y: 250,
        },
        {
            type: "ellipse",
            x: 250,
            y: 250,
        },
        {
            type: "diamond",
            x: 380,
            y: 250,
        },
    ]);

    let lastMessage: string;


    const handleValueChange = (selectedValue: string) => {
        console.log("Selected value: ", selectedValue);
        setSelectedFileId(selectedValue);
    };
    async function convertmermaidsyntax(lastMessage: string) {
        try {
            console.log("flowchart by gpt"+lastMessage);
            let { elements, files } = await parseMermaidToExcalidraw(lastMessage);
            excalidrawElements = convertToExcalidrawElements(elements);
            setIsReady(true);
        } catch (e) {
            console.error('Error initializing Excalidraw:', e);
            toast({
                variant: "destructive",
                title: "Uh oh! Something went wrong.",
                description: "There was a problem with your request.",
                action: <ToastAction altText="Try again">Try again</ToastAction>,
            })
        }
    }
    


    const { messages, input, handleInputChange, handleSubmit, isLoading, data } = useChat({
        api: "/api/flowchart",
        onFinish(message) {
            if (message.role === "assistant") {
                lastMessage = message.content;
            }
            convertmermaidsyntax(lastMessage)
        },
        onError: (error) => {
            toast({
                variant: "destructive",
                title: "Uh oh! Something went wrong.",
                description: "There was a problem with your request.",
                action: <ToastAction altText="Try again">Try again</ToastAction>,
            })
        },
    });



    return (
        <main className='mx-auto max-w-7xl md:p-6 mb-6 h-screen'>

            <Card className="w-full h-full">
                <ResizablePanelGroup direction="vertical">
                    <ResizablePanel defaultSize={25} maxSize={25}>
                        <CardHeader>

                            <Card className='w-1/2'>
                                <form className='mx-2 my-2' onSubmit={handleSubmit}>
                                    <Select onValueChange={handleValueChange}>
                                        <SelectTrigger className="w-[280px]">
                                            <SelectValue placeholder="Select a file" />
                                        </SelectTrigger>
                                        <SelectContent >
                                            {files && files.length > 0 ? (
                                                files.map((file) => (
                                                    <SelectItem key={file.id} value={file.id}>
                                                        {file.name}
                                                    </SelectItem>
                                                ))
                                            ) : (
                                                <SelectItem value="none">
                                                    None
                                                </SelectItem>
                                            )}
                                        </SelectContent>
                                    </Select>

                                    <div className="w-full flex gap-2 my-3" >
                                        <Input
                                            placeholder="How Can I help you?"
                                            value={input}
                                            onChange={handleInputChange}
                                        />
                                        <Button type="submit" className='bg-black hover:bg-slate-600'
                                            onClick={async () => {
                                                let fileId = selectedFileId;;
                                                const updatedfile = await updatefileselection(fileId)
                                            }}
                                        >{isLoading ? <Loader2 className='animate-spin' /> : "Send"}</Button>

                                    </div>
                                </form>
                            </Card>

                        </CardHeader>
                    </ResizablePanel>
                    {/* <CardContent>  */}
                    <ResizableHandle withHandle />
                    <ResizablePanel defaultSize={75}>
                        <Card className='mx-6 h-[600px] mt-2'>
                            {isReady ? (
                                <Excalidraw
                                    initialData={{
                                        elements: excalidrawElements,
                                    }}
                                />
                            ) : (
                                <ExcalidrawGuide />
                            )}
                        </Card>
                    </ResizablePanel>
                </ResizablePanelGroup>
            </Card >

        </main >
    )
}

export default Flowchartdashboard;
```

**Comment by ad1992** [comment]
@suzushi-tw the docs for [next js integration](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#nextjs) has been updated with examples, let me know if it still doesn't work for you

**Comment by leojkwan** [comment]
Can you explain what the fix is? I'm also running into the same issue and making sure Excalidraw is loaded on Client side.

```
GET /system-design/design-rate-limiter 500 in 104ms
 ⨯ ReferenceError: document is not defined
    at __webpack_require__ (/Users/leokwan/Development/mobiledevcombine-web/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/leokwan/Development/mobiledevcombine-web/.next/server/webpack-runtime.js:33:43)
    at eval (./app/system-design/[slug]/page.tsx:12:80)
    at (ssr)/./app/system-design/[slug]/page.tsx (/Users/leokwan/Development/mobiledevcombine-web/.next/server/app/system-design/[slug]/page.js:260:1)
    at Object.__webpack_require__ [as require] (/Users/leokwan/Development/mobiledevcombine-web/.next/server/webpack-runtime.js:33:43)
```
