### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c yarn build:app:docker" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by zuoyangs** [excalidraw/excalidraw#7582]
[root@VM-4-8-centos excalidraw-0.17.0]# docker build -f Dockerfile -t xxxxxx.com(马赛克)/excalidraw:0.17.0 .
[+] Building 2.5s (12/13)                                                                                                                                    docker:default
 => [internal] load build definition from Dockerfile                                                                                                                   0.0s
 => => transferring dockerfile: 379B                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                      0.0s
 => => transferring context: 171B                                                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/node:18                                                                                                             1.4s
 => [internal] load metadata for docker.io/library/nginx:1.21-alpine                                                                                                   1.4s
 => [build 1/6] FROM docker.io/library/node:18@sha256:995a5f4314885452a4a785abc25a0fec40e26c346559e11e709d58bb7a927cf4                                                 0.0s
 => CACHED [stage-1 1/2] FROM docker.io/library/nginx:1.21-alpine@sha256:a74534e76ee1121d418fa7394ca930eb67440deda413848bc67c68138535b989                              0.0s
 => [internal] load build context                                                                                                                                      0.0s
 => => transferring context: 28.15kB                                                                                                                                   0.0s
 => CACHED [build 2/6] WORKDIR /opt/node_app                                                                                                                           0.0s
 => CACHED [build 3/6] COPY package.json yarn.lock ./                                                                                                                  0.0s
 => CACHED [build 4/6] RUN yarn --ignore-optional --network-timeout 600000                                                                                             0.0s
 => CACHED [build 5/6] COPY . .                                                                                                                                        0.0s
 => ERROR [build 6/6] RUN yarn build:app:docker                                                                                                                        0.9s
------
 > [build 6/6] RUN yarn build:app:docker:
0.431 yarn run v1.22.19
0.480 $ cross-env VITE_APP_DISABLE_SENTRY=true VITE_APP_DISABLE_TRACKING=true vite build
0.821 vite v4.4.2 building for production...
0.845 Could not resolve entry module "index.html".
0.848 error during build:
0.848 RollupError: Could not resolve entry module "index.html".
0.848     at error (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
0.848     at ModuleLoader.loadEntryModule (file:///opt/node_app/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24671:20)
0.848     at async Promise.all (index 0)
0.848 ✓ 0 modules transformed.
0.848 ✓ built in 20ms
0.871 error Command failed with exit code 1.
0.872 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
Dockerfile:11
--------------------
   9 |
  10 |     COPY . .
  11 | >>> RUN yarn build:app:docker
  12 |
  13 |     FROM nginx:1.21-alpine
--------------------
ERROR: failed to solve: process "/bin/sh -c yarn build:app:docker" did not complete successfully: exit code: 1

**Comment by stanlog** [comment]
Same error here. Image builds tries from main repo, and last tag archive, same behavior.

**Comment by anshibanov** [comment]
Same error ( Any updates here?

**Comment by tibuski** [comment]
Idem

**Comment by xvzhenduo** [comment]
Same error

**Comment by jcobol** [comment]
I ran a `git bisect` session on the repo.  To test each revision, it ran `docker-compose build`. Here's the `git bisect log` output:
```
$ git bisect log
git bisect start 'bad'
# bad: [15bfa626b41c3981aed557666f67be3453243b29] feat: support to not render remote cursor & username (#7130)
git bisect bad 15bfa626b41c3981aed557666f67be3453243b29
# bad: [d6cd8b78f11742e9107dd4cd9cee564120ae599b] build: decouple package deps and introduce yarn workspaces (#7415)
git bisect bad d6cd8b78f11742e9107dd4cd9cee564120ae599b
# good: [d36c72c435060a913f9c0045b4f572cc2e42d882] fix: don't show `canvasBackground` label when `UIOptions.canvasActions.changeViewBackgroundColor` is false (#6781)
git bisect good d36c72c435060a913f9c0045b4f572cc2e42d882
# bad: [7ad02c359ae64bae28eb5b59b783c5d858cd12bc] fix: memoize static canvas on `props.renderConfig` (#7131)
git bisect bad 7ad02c359ae64bae28eb5b59b783c5d858cd12bc
# bad: [188921c24753e37aaa64939eea6ca4ec491bec29] fix: grid jittery after partition PR (#6935)
git bisect bad 188921c24753e37aaa64939eea6ca4ec491bec29
# bad: [b85d5fa12b4d50e34458439eb084f205ae49ce88] test: add coverage report for PR (#6840)
git bisect bad b85d5fa12b4d50e34458439eb084f205ae49ce88
# bad: [48924688c75aada554674b5a2bc3c752d33d3444] build: migrate to Vite 🚀 (#6818)
git bisect bad 48924688c75aada554674b5a2bc3c752d33d3444
# bad: [dcc75ed0075f16898340aff665f7c1f0b13c8a1a] feat: adds support for stackblitz.com embeds (#6813)
git bisect bad dcc75ed0075f16898340aff665f7c1f0b13c8a1a
# good: [b57b3b573da874f7527589c10632ec936c1962d2] feat: introducing Web-Embeds (alias iframe element) (#6691)
git bisect good b57b3b573da874f7527589c10632ec936c1962d2
# bad: [e93bbc577613a6de6bb43c40c3b57286b4994ca5] build: Migrate to Vite 🚀 (#6713)
git bisect bad e93bbc577613a6de6bb43c40c3b57286b4994ca5
# good: [2a2495175b9d8be6a7140158ba6a958b14374f76] build: increase limit to 290 kB for prod bundle (#6809)
git bisect good 2a2495175b9d8be6a7140158ba6a958b14374f76
# first bad commit: [e93bbc577613a6de6bb43c40c3b57286b4994ca5] build: Migrate to Vite 🚀 (#6713)
```

**Comment by simarmannsingh** [comment]
The PR [#7806](https://github.com/excalidraw/excalidraw/pull/7806) solved this error for me for the `linux/arm64` platform.
