### ISSUE TITLE
Unable to use excalidraw in browser extension [CSP lvl. 3]

### ISSUE THREAD

**Issue by krzysztofMlczk** [excalidraw/excalidraw#7657]
I am trying to use excalidraw inside chrome extension that injects excalidraw into a webpage but I am not able to due to strict CSPs. Excalidraw depends on some remote resources from https://unpkg.com/ but it is mentioned in the documentation that it is possible to host those files by myself. And that is what I am doing in my extension. However in order to make excalidraw actually use the local version of those files instead of the remote one I need to set window.EXCALIDRAW_ASSET_PATH to chrome.runtime.getURL("") (that's where these files reside) but it is not possible as fetching of those resources happens from the top level window (the webpage) and not content script. I cannot set global variables of the webpage as extensions content sripts live in an isolated world, where only DOM is shared between content script and the webpage. I tried to set this variable by injecting inline script (since DOM is the only shared thing) but this is not allowed due to strict CSPs of chrome extensions. I really do need a way to force excalidraw to use my local resources but I don't want to modify code of the library.

**Comment by jtmuller5** [comment]
I am hitting this issue too:

> excalidraw.development.js:4347 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at ./entry.js (excalidraw.development.js:4347:1)
    at __webpack_require__ (excalidraw.development.js:5625:42)
    at excalidraw.development.js:5889:37
    at excalidraw.development.js:5892:12
    at webpackUniversalModuleDefinition (excalidraw.development.js:17:27)
    at excalidraw.development.js:18:3
