### ISSUE TITLE
Build for React from Fork

### ISSUE THREAD

**Issue by johnrbnsn** [excalidraw/excalidraw#8320]
I have created a fork of the main excalidraw repo which I've made some personalizing changes to. I would like to use this fork as a dependency in my original react app. I've added the git repo as a dependency, but I get a bunch of `[vite] Pre-transform error: Failed to resolve import "open-color" from "node_modules/excalidraw-git/packages/excalidraw/components/icons.tsx". Does the file exist? (x12)` errors (not just open-color, also 'roughjs/bin/math', 'points-on-curve', 'sass' and others.) I have already run 'npm install' on the directory, and the project works fine when I use the `import {Excalidraw} from '@excalidraw/excalidraw'` import.

In my project:

package.json

```
{
  "name": "excalidraw-test",
  ...
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "lint": "eslint . --ext js,jsx --report-unused-disable-directives --max-warnings 0",
    "preview": "vite preview"
  },
  "dependencies": {
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "excalidraw-git": "github:excalidraw/excalidraw",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
```

App.jsx top imports:

```
import { useEffect, useState } from 'react'
import { Button, Excalidraw, MainMenu, exportToSvg, getFreeDrawSvgPath } from 'excalidraw-git/excalidraw-app'
```

**Question:
How can I use the github repo as a dependency in my code, or is there another way I should be using my modified excalidraw code as a dependency?**

**Comment by dwelle** [comment]
Hi. You're trying to use the whole repo as a dependency? Or to put it differently, you're trying to use the Vite app (`excalidraw-app/`, the thing you see on excalidraw.com) as opposed to the excalidraw package (`packages/excalidraw`)?

That's not gonna work (at least not easily), as the repo is a monorepo of multiple packages and apps.

**Comment by johnrbnsn** [comment]
Hi @dwelle , I appreciate your response. I'm trying to make some modifications to the source for my project, and then build the equivalent to what I can install with `npm i @excalidraw/excalidraw`. Is there another repo I should be looking to clone/ use? Or am I referencing the wrong part of the repo with my 'import' / dependency statement? I'm sorry, I realize these are probably really basic questions.

**Comment by dwelle** [comment]
I see. In that sense you can't use the repo as dependency because it's a monorepo, while you're interested in the excalidraw package (in the repo located in `packages/excalidraw`).

It may be technically possible to do it the way you suggest (installing from gh repo), but I haven't tried it.

Try looking into https://docs.npmjs.com/cli/v10/using-npm/config#prefix. You'll also need to setup `scripts.prepare` in the `packages/excalidraw/package.json` to run the build after installation.

**Comment by johnrbnsn** [comment]
I'll take a look, thanks for pointing me in that direction! If I figure it out I'll comment back here with instructions for future devs.

**Comment by johnrbnsn** [comment]
# Question #

@dwelle thank you for your advice, I've been trying to get this to work. The simplest version of what I'm trying to do is recreate what is installed with `npm install @excalidraw/excalidraw`, do you have a recommended workflow for this? I think I've got the build process down, but I'm struggling to use the result in my app once I've built the code.

-------------------------

#  What I've tried so far #

## Building with Changes ##

I've tried to get this to work with the following based on your advice about the `packages/excalidraw` target:

1. Clone git repo in Linux (build script doesn't run on windows due to rm not existing on windows)
2. npm install yarn
3. npm run start
4. cd to the 'packages' directory (./packages/excalidraw)
5. npm run build:esm 

This will give me a `/dist/browser/dev` folder and an `index.js` which has the correct exports (`Excalidraw, MainMenu, exportToSvg...`) that I should be able to use in my code. 

## Installation ##

I have tried to "install" this built directory with npm (`> npm install \\\\wsl.localhost\Ubuntu\home\john\code\tmp_excalidraw\excalidraw\packages\excalidraw`). This is then reflected in my projects `package.json`, but always returns `Error: The following dependencies are imported but could not be resolved: @excalidraw/excalidraw-local (imported by C:/Users/John/Code/gpmap-excalidraw/src/App.jsx)` when I run my project, and the `@excalidraw/excalidraw-local` does not exist in my node_modules folder.

I also tried to use the built packages directory as a copy/ paste in my project, importing with `import { Excalidraw, MainMenu, exportToSvg, getFreeDrawSvgPath } from './excalidraw-local/index'` When I try this route, I get a browser error from `cons.tsx:9:19` stating `ReferenceError: React is not defined`, even though I do have react defined for my project.

---------------------------------

Again, thanks for your help and apologies for the rookie questions. I imagine I'm not the only one having these issues, so I can prepare a good guide once resolved.

**Comment by Dev4Naanal** [comment]
Hi @johnrbnsn,.. The same way I am trying to use the excalidraw as a local package in my react application. 

Here’s how you can modify your script to work on Windows:

Replace `rm -rf` with `rmdir /s /q` for directories.
Replace `rm` with `del` for files.

For using the excalidraw as a package you can try `npm link`

Go to your `D:\Project\excalidraw\packages\excalidraw>yarn build:esm`


```
D:\Project\excalidraw\packages\excalidraw>yarn link 
yarn link v1.22.22
success Registered "@excalidraw/excalidraw".
info You can now run `yarn link "@excalidraw/excalidraw"` in the projects where you want to use this package and it will be used instead.
Done in 0.07s.
```

Then in my react app
```
D:\Project\MyReactApp>yarn link "@excalidraw/excalidraw"

yarn link v1.22.22
success Using linked package for "@excalidraw/excalidraw".
Done in 0.07s.
```

Then I used the excalidraw in my component as 

`import { Excalidraw, Footer } from "@excalidraw/excalidraw";`

When I hover the `@excalidraw/excalidraw` it is imported from `D:\Project\excalidraw\packages\excalidraw`. Also I checked the `node_modules` where `@excalidraw/excalidraw` is available,. no need to manually copy the files.

In this stage, I got error in MyReactApp. Cant able to start the app.

```
ERROR in ../excalidraw/packages/excalidraw/dist/dev/index.js 1139:0-42
Module not found: Error: Can't resolve 'roughjs/bin/math' in 'D:\Project\excalidraw\packages\excalidraw\dist\dev'
Did you mean 'math.js'?
BREAKING CHANGE: The request 'roughjs/bin/math' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
ERROR in ../excalidraw/packages/excalidraw/dist/dev/index.js 2106:0-55
Module not found: Error: Can't resolve 'roughjs/bin/generator' in 'D:\Project\excalidraw\packages\excalidraw\dist\dev'
Did you mean 'generator.js'?
BREAKING CHANGE: The request 'roughjs/bin/generator' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
ERROR in ../excalidraw/packages/excalidraw/dist/dev/index.js 11049:0-38
Module not found: Error: Can't resolve 'roughjs/bin/rough' in 'D:\Project\excalidraw\packages\excalidraw\dist\dev'
Did you mean 'rough.js'?
BREAKING CHANGE: The request 'roughjs/bin/rough' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

So what I did is in `D:\Project\excalidraw\packages\excalidraw\dist\dev\index.js` for testing. It is not advisable to change the code in `dist` folder.

updated the import statements in `index.js` file to include the `.js` extension

```
import rough from 'roughjs/bin/rough.js';
import math from 'roughjs/bin/math.js';
import generator from 'roughjs/bin/generator.js';
```

Then I can able to run MyReactApp. Again I got error in the component where I imported Excalidraw

```
Uncaught TypeError: Cannot read properties of null (reading 'useEffect')
    at useEffect (react.development.js:1634:1)
    at ExcalidrawBase (index.tsx:84:1)
    at renderWithHooks (react-dom.development.js:15486:1)
    at mountIndeterminateComponent (react-dom.development.js:20103:1)
    at beginWork (react-dom.development.js:21626:1)
    at beginWork$1 (react-dom.development.js:27465:1)
    at performUnitOfWork (react-dom.development.js:26596:1)
    at workLoopSync (react-dom.development.js:26505:1)
    at renderRootSync (react-dom.development.js:26473:1)
    at recoverFromConcurrentError (react-dom.development.js:25889:1)
```

Any documentation/guide/link available to use local excalidraw package in another application will be helpful @dwelle

**Comment by dev4tg** [comment]
Before `Uncaught TypeError: Cannot read properties of null (reading 'useEffect')`

I got `node-fetch` require error in `D:\Project\excalidraw\scripts\woff2\woff2-esbuild-plugins.js`

```
D:\Project\excalidraw\packages\excalidraw>yarn build:esm
yarn run v1.22.22
$ node ../../scripts/buildPackage.js && yarn gen:types
D:\Project\excalidraw\scripts\woff2\woff2-esbuild-plugins.js:5
const fetch = require("node-fetch");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module D:\Project\excalidraw\node_modules\node-fetch\src\index.js from D:\Project\excalidraw\scripts\woff2\woff2-esbuild-plugins.js not supported.
Instead change the require of index.js in D:\Project\excalidraw\scripts\woff2\woff2-esbuild-plugins.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (D:\Project\excalidraw\scripts\woff2\woff2-esbuild-plugins.js:5:15) {
  code: 'ERR_REQUIRE_ESM'
}
```

I have removed the `fetchRetry` function from `module.exports.woff2ServerPlugin`. And modified that function as below and placed as first function in that file.

```
async function fetchWithRetry(url, options = {}, retries = 0, delay = 1000) {
  const fetch = (await import("node-fetch")).default;

  try {
    const response = await fetch(url, options);

    if (!response.ok) {
      throw new Error(`Status: ${response.status}, ${await response.json()}`);
    }

    return response;
  } catch (e) {
    if (retries > 0) {
      await new Promise((resolve) => setTimeout(resolve, delay));
      return fetchWithRetry(url, options, retries - 1, delay * 2);
    }

    console.error(`Couldn't fetch: ${url}, error: ${e.message}`);
    throw e;
  }
}

```

and update the fetchRetry with fetchWithRetry in line 107 after added new function.

```
if (path.isAbsolute(args.path)) {
    // read local woff2 as a buffer (WARN: `readFileSync` does not work!)
    woff2Buffer = await fs.promises.readFile(args.path);
  } else {
    // fetch remote woff2 as a buffer (i.e. from a cdn)
    const response = await fetchWithRetry(args.path, {}, 3);    // updated this line function
    woff2Buffer = await response.buffer();
  }
```

After the above function change I can able to resolve the error `node-fetch` require error.

==============

For `roughjs` error in `D:\Project\excalidraw\packages\excalidraw\dist\dev\index.js`

I wrote a separate script to change the import with extension

`D:\Project\excalidraw\packages\excalidraw\fix-imports.mjs`

```
import fs from 'fs';
import path from 'path';

const filePath = path.join(process.cwd(), 'dist', 'dev', 'index.js');
let content = fs.readFileSync(filePath, 'utf8');

content = content.replace(/roughjs\/bin\/rough/g, 'roughjs/bin/rough.js');
content = content.replace(/roughjs\/bin\/math/g, 'roughjs/bin/math.js');
content = content.replace(/roughjs\/bin\/generator/g, 'roughjs/bin/generator.js');

fs.writeFileSync(filePath, content, 'utf8');
```
Added this script in `package.json`

```
"scripts": {
   ....
    "postbuild": "node fix-imports.mjs"
 }
```

=======

So to resolve the `Uncaught TypeError: Cannot read properties of null (reading 'useEffect')` error. I have created a symlink for my apps `react` and `react-dom`

```
D:\Project\MyReactApp\node_modules\react>yarn link
yarn link v1.22.22
success Registered "react".
info You can now run `yarn link "react"` in the projects where you want to use this package and it will be used instead.
Done in 0.08s.
```

```
D:\Project\MyReactApp\node_modules\react-dom>yarn link       
yarn link v1.22.22
success Registered "react-dom".
info You can now run `yarn link "react-dom"` in the projects where you want to use this package and it will be used instead.
Done in 0.07s.
```

Then in my `D:\Project\excalidraw\packages\excalidraw`

```
D:\Project\excalidraw\packages\excalidraw>yarn link react                              
yarn link v1.22.22
success Using linked package for "react".
Done in 0.12s.
```

```
D:\Project\excalidraw\packages\excalidraw>yarn link react-dom
yarn link v1.22.22
success Using linked package for "react-dom".
Done in 0.15s.
```

```
D:\Project\excalidraw\packages\excalidraw>yarn build:esm
yarn run v1.22.22
$ node ../../scripts/buildPackage.js && yarn gen:types
$ tsc
Done in 23.43s.
```

```
D:\Project\excalidraw\packages\excalidraw>yarn postbuild
yarn run v1.22.22
$ node fix-imports.mjs
Done in 0.28s.
```

After this I can able to see excalidraw imported into my react app but still css issue.

 `GET https://unpkg.com/@excalidraw/excalidraw@0.17.6/dist/prod/CascadiaCode-Regular-TMZI7IJ5.woff2 net::ERR_ABORTED 404 (Not Found)`
 
 So for this I have imported the css directly into my react app where Excalidraw is imported.
```
import { Excalidraw } from "@excalidraw/excalidraw";
import "@excalidraw/excalidraw/index.css";
```
 
 Now I can able to use the excalidraw as a local package using npm link :). for any changes in excalidraw to reflect in my react app, each time I need to rebuild the package. 
 
` D:\Project\excalidraw\packages\excalidraw>yarn build:esm`
