### ISSUE TITLE
How to publish packages/excalidraw to npmjs.com

### ISSUE THREAD

**Issue by guinanlin** [excalidraw/excalidraw#8527]
**What I want to do ?**
I want to publish custom packages/excalidraw to the npm site, and then I need to integrate it into the application system. Now I don't know how to publish it to the npm site?

I have tried the following methods, but cannot get my answer.

**Method 1st:**
1. fork project

2. execute following script:

  ```
  rm yarn.lock
  ```  

3. /home/excalidraw/packages/excalidraw to execute

  ```
  1. yarn gen:types
     yarn build.esm
     yarn pack
  
  "scripts": {
  "gen:types": "rm -rf types && tsc",
  "build:esm": "rm -rf dist && node ../../scripts/buildPackage.js && yarn gen:types",
  "pack": "yarn build:umd && yarn pack",
  "start": "node ../../scripts/buildExample.mjs && vite",
  "build:example": "node ../../scripts/buildExample.mjs",
  "size": "yarn build:umd && size-limit"
  }
  ```

  

4. npm login, npm publish will publish well

**However, the file structure of the published npm package is different from the file structure of the npm package published on the official website.**
https://www.npmjs.com/package/@excalidraw/excalidraw?activeTab=code

https://www.npmjs.com/package/excalidraw-zh?activeTab=code

**method 2nd:**
1. fork project

2. update \packages\excalidraw\package.json  key=name

3. update .github\workflows\autorelease-excalidraw.yml to workflow_dispatch: to Allow manual submission

4. add some comments in files

5. run action autorelease-excalidraw.yml will happen the following errors:

```
dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
error Command failed with exit code 2.
error Command failed with exit code 2.
Error: Command failed: yarn run build:esm
error Command failed with exit code 2.
error Command failed with exit code 2.

    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at publish (/home/runner/work/excalidraw/excalidraw/scripts/autorelease.js:21:5)
    at /home/runner/work/excalidraw/excalidraw/scripts/autorelease.js:71:3
    at ChildProcess.exithandler (node:child_process:414:7)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:517:28) {
  status: 2,
  signal: null,
  output: [
    null,
    <Buffer 24 20 72 6d 20 2d 72 66 20 64 69 73 74 20 26 26 20 6e 6f 64 65 20 2e 2e 2f 2e 2e 2f 73 63 72 69 70 74 73 2f 62 75 69 6c 64 50 61 63 6b 61 67 65 2e 6a ... 5322 more bytes>,
    <Buffer 65 72 72 6f 72 20 43 6f 6d 6d 61 6e 64 20 66 61 69 6c 65 64 20 77 69 74 68 20 65 78 69 74 20 63 6f 64 65 20 32 2e 0a 65 72 72 6f 72 20 43 6f 6d 6d 61 ... 28 more bytes>
  ],
  pid: 1973,
  stdout: <Buffer 24 20 72 6d 20 2d 72 66 20 64 69 73 74 20 26 26 20 6e 6f 64 65 20 2e 2e 2f 2e 2e 2f 73 63 72 69 70 74 73 2f 62 75 69 6c 64 50 61 63 6b 61 67 65 2e 6a ... 5322 more bytes>,
  stderr: <Buffer 65 72 72 6f 72 20 43 6f 6d 6d 61 6e 64 20 66 61 69 6c 65 64 20 77 69 74 68 20 65 78 69 74 20 63 6f 64 65 20 32 2e 0a 65 72 72 6f 72 20 43 6f 6d 6d 61 ... 28 more bytes>
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```
I have try to serach the isses, but there is no answer, and try to read the document 
https://docs.excalidraw.com/docs/@excalidraw/excalidraw/development

expect to get reply from excalidraw team , tks

**Comment by arjunacharya10** [comment]
I had run into a similar issue. The problem is with @excalidraw/mermaid-to-excalidraw, so there is a cyclical dependency of that repository to @excalidraw/excalidraw, so when you rename the name in packages/excalidraw/package.json, you get the error. WHich is why when making custom build, you will have to remove all code related to @excalidraw/mermaid-to-excalidraw and remove @excalidraw/mermaid-to-excalidraw from package.json as well and then try building and releasing.
