### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'user')

### ISSUE THREAD

**Issue by vital000** [excalidraw/excalidraw#8933]
The board server hangs after some time. This error: 
file:///root/whiteboard/websocket_server/SocketManager.js:160 
                                user: data.user, 
                                           ^ 
 
TypeError: Cannot read properties of undefined (reading 'user') 
    at file:///root/whiteboard/websocket_server/SocketManager.js:160:16 
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) 
    at async Promise.all (index 0) 
    at async SocketManager.joinRoomHandler (file:///root/whiteboard/websocket_server/SocketManager.js:170:29) 

What can be checked or corrected? Thank you.

**Comment by Silver-Golden** [comment]
I am also impacted by this, my log, slightly cut down and :

``ABC`` = ``cadie nextcloud-whiteboard-server[10832]``

```
Jan 06 19:55:01 ABC: [50678] Syncing room data
Jan 06 19:55:01 ABC: [50678] Room data synced. Users: 1, Last edited by: b141f272-a0b5-103d-9494-33f42d2d21f3, files: 0
Jan 06 20:14:49 ABC: [token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.part1>
Jan 06 20:15:13 ABC: [token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.part1>
Jan 06 20:15:28 ABC: [token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.part2>
Jan 06 20:16:38 ABC: [token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.part2>
Jan 06 20:16:38 ABC: [socket:x5lFNOzjg9zJmJ8bAAAJ] Disposing room
Jan 06 20:25:01 ABC: [50678] Disposing room
Jan 06 20:25:01 ABC: [50678] Saving room data to server: 110 elements, 0 files
Jan 06 21:18:30 ABC: decodedData {
Jan 06 21:18:30 ABC:   userid: 'af55d1a0-0a5d-103f-889d-5f19812274de',
Jan 06 21:18:30 ABC:   fileId: 50678,
Jan 06 21:18:30 ABC:   isFileReadOnly: false,
Jan 06 21:18:30 ABC:   user: { id: 'af55d1a0-0a5d-103f-889d-5f19812274de', name: 'Firstname Surname' },
Jan 06 21:18:30 ABC:   iat: 1736198310,
Jan 06 21:18:30 ABC:   exp: 1736199210
Jan 06 21:18:30 ABC: }
Jan 06 21:18:30 ABC: [50678] i2ZWQQge5iW6BJkEAAAL has joined 50678
Jan 06 21:18:30 ABC: file:$EXCALIDRAW_DIR/lib/node_modules/whiteboard/websocket_server/SocketManager.js:160
Jan 06 21:18:30 ABC:                                 user: data.user,
Jan 06 21:18:30 ABC:                                            ^
Jan 06 21:18:30 ABC: TypeError: Cannot read properties of undefined (reading 'user')
Jan 06 21:18:30 ABC:     at file:$EXCALIDRAW_DIR/lib/node_modules/whiteboard/websocket_server/SocketManager.js:160:16
Jan 06 21:18:30 ABC:     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
Jan 06 21:18:30 ABC:     at async Promise.all (index 0)
Jan 06 21:18:30 ABC:     at async SocketManager.joinRoomHandler (file:$EXCALIDRAW_DIR/lib/node_modules/whiteboard/websocket_server/Soc>
Jan 06 21:18:30 ABC: Node.js v22.11.0
```
